{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "95dade8d-3021-496c-8fb1-4ded40e97a30",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CSV file created: Dirty_Gallery_Sales_Data.csv\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from datetime import datetime, timedelta\n",
    "import random\n",
    "\n",
    "np.random.seed(42)\n",
    "random.seed(42)\n",
    "\n",
    "artists = [\n",
    "    'Alison Johnson', 'Andrei Protsouk', 'Kimberley Harris', 'Benoit Havard',\n",
    "    'Linda Charles', 'Nigel Cooke', 'Alexander Weaver', 'Amber Tyldesley',\n",
    "    'Craig Alan', 'Doug Hyde', 'Fabian Perez', 'Henderson Cisz',\n",
    "    'Jeff Rowland', 'Mackenzie Thorpe', 'Rozanne Bell'\n",
    "]\n",
    "\n",
    "artwork_types = ['Print', 'Original', 'Sculpture (small)']\n",
    "\n",
    "age_groups = ['18-24', '25-34', '35-44', '45-54', '55+']\n",
    "\n",
    "payment_methods = ['Card', 'Cash', 'Bank Transfer']\n",
    "\n",
    "num_rows = 420\n",
    "start_date = datetime(2024, 1, 1)\n",
    "end_date   = datetime(2024, 12, 31)\n",
    "num_days   = (end_date - start_date).days + 1\n",
    "\n",
    "dates = [start_date + timedelta(days=random.randint(0, num_days-1)) for _ in range(num_rows)]\n",
    "random.shuffle(dates)\n",
    "\n",
    "df = pd.DataFrame({\n",
    "    'Sale_ID': range(10001, 10001 + num_rows),\n",
    "    'SaleDate': dates,\n",
    "    'Artist': random.choices(artists, k=num_rows),\n",
    "    'ArtworkType': random.choices(artwork_types, weights=[0.62, 0.29, 0.09], k=num_rows),\n",
    "    'Title': [f\"{random.choice(['Liminal','Urban','Coastal','Sunset','Abstract','Floral','Geometric','Equilibrium','Whispers','Pulse'])} \"\n",
    "              f\"{random.choice(['Spaces','Reflections','Harmony','Memory','Flow','Dream','Echo','in Blue','Pulse','Horizon'])}\"\n",
    "              for _ in range(num_rows)],\n",
    "})\n",
    "\n",
    "df['Price_GBP'] = df['ArtworkType'].apply(\n",
    "    lambda t: round(random.uniform(480, 1580), 2) if t == 'Print' else\n",
    "              round(random.uniform(1950, 6200), 2) if t == 'Original' else\n",
    "              round(random.uniform(1400, 4200), 2)\n",
    ")\n",
    "\n",
    "df['Quantity'] = df['ArtworkType'].apply(\n",
    "    lambda t: 1 if t in ['Original', 'Sculpture (small)'] else random.choices([1,2], weights=[0.84,0.16])[0]\n",
    ")\n",
    "\n",
    "df['Total_GBP'] = (df['Price_GBP'] * df['Quantity']).round(2)\n",
    "\n",
    "df['PaymentMethod'] = random.choices(payment_methods, weights=[0.73, 0.17, 0.10], k=num_rows)\n",
    "df['BuyerType']    = random.choices(['New','Repeat'], weights=[0.69, 0.31], k=num_rows)\n",
    "df['AgeGroup']     = random.choices(age_groups, weights=[0.11, 0.27, 0.29, 0.23, 0.10], k=num_rows)\n",
    "\n",
    "# Generating the dirty data below -----------------------------------------------------------------------------------------------------------------\n",
    "\n",
    "dup_idx = df.sample(frac=0.095).index\n",
    "duplicates = df.loc[dup_idx].copy()\n",
    "duplicates['Sale_ID'] = duplicates['Sale_ID'].astype(str) + '_dup'\n",
    "df = pd.concat([df, duplicates], ignore_index=True)\n",
    "\n",
    "df.loc[df.sample(frac=0.07).index, 'AgeGroup'] = np.nan\n",
    "df.loc[df.sample(frac=0.035).index, 'Total_GBP'] = np.nan\n",
    "\n",
    "df['AgeGroup'] = df['AgeGroup'].replace({\n",
    "    '35-44': '35 - 44', '45-54': '45to54', '55+': '55 plus', np.nan: 'UNK'\n",
    "})\n",
    "\n",
    "df['PaymentMethod'] = df['PaymentMethod'].replace({\n",
    "    'Card': random.choice(['card','CARD','Credit Card','Debit Card','CC'])\n",
    "})\n",
    "\n",
    "df.loc[df.sample(frac=0.018).index, 'Quantity'] = -1\n",
    "df.loc[df.sample(frac=0.022).index, 'Price_GBP'] = 0\n",
    "df.loc[df.sample(frac=0.014).index, 'Total_GBP'] = -450.75\n",
    "\n",
    "df.loc[df.sample(frac=0.021).index, 'SaleDate'] += timedelta(days=random.randint(180, 600))\n",
    "\n",
    "artist_variations = {\n",
    "    'Alison Johnson': ['A. Johnson', 'Alison J', 'Alisonjohnson'],\n",
    "    'Andrei Protsouk': ['Andrei P', 'A Protsouk'],\n",
    "}\n",
    "for artist, variants in artist_variations.items():\n",
    "    mask = df['Artist'] == artist\n",
    "    if mask.any():\n",
    "        df.loc[mask & (np.random.rand(len(df)) < 0.15), 'Artist'] = random.choice(variants)\n",
    "\n",
    "df = df.sample(frac=1).reset_index(drop=True)\n",
    "\n",
    "output_file = 'Dirty_Gallery_Sales_Data.csv'\n",
    "\n",
    "df.to_csv(\n",
    "    output_file,\n",
    "    index=False\n",
    ")\n",
    "\n",
    "print(f\"CSV file created: {output_file}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
